config:
  target: http://service-example.localhost
  phases:
    - duration: 100
      arrivalRate: 3

scenarios:
  - flow:
      - get:
          url: "/checkout"
  - flow:
      - get:
          url: "/bad"
